apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-product
  labels:
    app: go-microservices-dm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: product
          image: 586050444726.dkr.ecr.eu-central-1.amazonaws.com/go-product-service:8df10ebc0b4e249953e69c77eb499520a69d8960
          ports:
            - containerPort: 8080

          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "500m"

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15  
            periodSeconds: 10
            failureThreshold: 3  
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3  
