apiVersion: v1
kind: Service
metadata:
  name: service-for-go
  namespace: dev
spec:
  selector:
    app.kubernetes.io/name: go-app
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80  # Service port
    targetPort: 8080  # Pod port