---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  clusterIP: None
  selector:
    app: postgres-db
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 5432
    targetPort: 5432
