replicas: 2

serviceAccount:
  annotation:
    <YOUR_ARN_IAM_ROLE_KARPENTER>

settings:
  interruptionQueueName: go-cluster-dev-karpenter-queue # Name SQS Queue. Karpenter checks it for scaling.
  clusterName: go-cluster-dev # Karpenter will create ec2 with label karpenter.sh/discovery/go-cluster-dev.
  defaultInstanceProfile: KarpenterNodeRole-go-cluster-dev


resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

logOptions:  # Level Filter 
  level: "info"
  format: "json"